project:
  name: fortaskcattesting2
  regions:
  - us-east-2
  template: lambdaLayers.yaml
tests:
  dev:
    parameters:
      Environment: "dev"
      ArtemisOpsBucket: "taskcat-assets-aabg"
  uat:
    parameters:
      Environment: "uat"
      ArtemisOpsBucket: "taskcat-assets-aabg"
  prod:
    parameters:
      Environment: "prod"
      ArtemisOpsBucket: "taskcat-assets-aabg"
