general:
  s3_bucket: taskcat-uploadproject
project:
  name: fortaskcattesting2
  regions:
  - us-west-2
  template: lambdaLayers.yaml
tests:
  dev-us-west-2:
    parameters:
      Environment: "dev"
      ProjectTeam: "Artemis"
      ProjectId:  "8675309"
      Version:  "0.1"
      ArtemisOpsBucket: "taskcat-assets-aabg-us-west-2"
  uat:
    parameters:
      Environment: "uat"
      ProjectTeam: "Artemis"
      ProjectId:  "8675309"
      Version:  "0.1"
      ArtemisOpsBucket: "taskcat-assets-aabg-us-west-2"
  prod:
    parameters:
      Environment: "prod"
      ProjectTeam: "Artemis"
      ProjectId:  "8675309"
      Version:  "0.1"
      ArtemisOpsBucket: "taskcat-assets-aabg-us-west-2"
