general:
  s3_bucket: taskcat-uploadproject
project:
  name: fortaskcattesting2
  regions:
  - us-east-2
  template: lambdaLayers.yaml
tests:
  dev:
    parameters:
      Environment: "dev"
      ArtemisOpsBucket: "taskcat-assets-aabg-us-east-2"
  uat:
    parameters:
      Environment: "uat"
      ArtemisOpsBucket: "taskcat-assets-aabg-us-east-2"
  prod:
    parameters:
      Environment: "prod"
      ArtemisOpsBucket: "taskcat-assets-aabg-us-east-2"
