project:
  name: fortaskcattesting
  regions:
#    - ap-northeast-1
#    - ap-northeast-2
#    - ap-south-1
#    - ap-southeast-1
#   - ap-southeast-2
#   - ca-central-1
#   - eu-central-1
#   - eu-west-1
#   - sa-east-1
#   - us-east-1
#   - us-east-2
#   - us-west-1
   - us-west-2
  reporting: true
tests:
  default:
    template: initial-infra.yaml
#    regions:
#      - us-east-1
#      - us-east-2
#      - us-west-1
#      - us-west-2
  # code-commit-pipeline-test:
  #   parameter_input: input-params-codecommit.json
  #   template_file: taskcat-ci-pipeline.yaml.template
  #   regions:
  #     - us-west-2
