project:
  name: fortaskcattesting
  regions:
  - us-west-2
  - eu-west-2
  - eu-west-3
  template: ./templates/lambdaLayers.yaml
tests:
  dev:
    parameters:
      Environment: "dev"
      ArtemisOpsBucket: "taskcat-assets"
